version: "3.9"

services:
  # proxy:
  #   container_name: proxy
  #   image: nginx:alpine
  #   ports:
  #     - "80:80"
  #   volumes:
  #     - ./nginx.conf:/etc/nginx/nginx.conf
  #   restart: "unless-stopped"
  #   networks:
  #     - backend

  # server:
  #   container_name: server
  #   build:
  #     context: ./
  #     dockerfile: Dockerfile.dev
  #   ports:
  #     - "3000:3000"
  #   volumes:
  #     - ./:/app
  #     - /app/node_modules
  #   restart: 'unless-stopped'
  #   networks:
  #     - backend
  mongodb:
    image: mongo:latest
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: secret
    ports:
      - 27017:27017
    volumes:
      - mongodb_data_container:/data/db
    networks:
       - backend

networks:
  backend:
    driver: bridge

volumes:
  data:
    driver: local
  mongodb_data_container:
